In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset1 =pd.read_excel('reg1.xlsx')
dataset2 =pd.read_excel('reg2.xlsx')
dataset= pd.concat([dataset1, dataset2])
print(dataset)

    direct  indirect  benefit
0     1498      3153     1995
1     1376      3106     1809
2     1168      3091     1808
3      859      3054     1674
4      752      3042     1564
5     1491      3039     1824
6     1476      3136     1994
7      745      3033     1563
8      833      3073     1692
9      867      3057     1686
10    1390      3152     1938
11    1425      3147     1975
12    1018      3087     1753
13    1173      3020     1650
14     833      3073     1692
15    1414      3131     1951
16     687      3022     1540
17     951      3050     1739
18     649      3027     1534
19    1373      3152     1995
20     772      3027     1577
21     753      3137     1565
22    1229      3147     1816
23    1419      3136     1611
24     729      3073     1561
25     821      3045     1616
26    1440      3114     1852
27     625      3020     1520
28     970      3032     1502
29     526      3146     1979
0     1504      3154     2003
1     1377      3112     1813
2     1175

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(dataset.loc[:, dataset.columns != 'benefit'], dataset['benefit'], test_size=0.20, random_state=42)

In [4]:
X_test

direct  indirect
0     1498      3153
5     1491      3039
6     1478      3141
15    1421      3138
13    1173      3020
24     736      3075
3      863      3057
18     656      3029
12    1018      3087
27     628      3021
16     695      3023
20     778      3029

In [5]:
y_test

0     1995
5     1824
6     2002
15    1956
13    1650
24    1563
3     1678
18    1541
12    1753
27    1527
16    1543
20    1578
Name: benefit, dtype: int64

In [6]:
from sklearn.svm import SVR
svr=SVR()
svr.fit(X_train, y_train)


SVR()

In [7]:
import numpy as np
import pandas as pd
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV, train_test_split

param_grid = {
    'kernel': ['linear'],
    'C': [0.1],
    'epsilon': [0.01],
    'gamma': ['scale', 'auto', 0.1, 1]
}

grid_search = GridSearchCV(estimator=svr, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)

grid_search.fit(X_train, y_train)

best_params = grid_search.best_params_
best_estimator = grid_search.best_estimator_

In [8]:
svr_predictions = best_estimator.predict(X_test)

In [9]:
svr_predictions

array([1987.80150016, 1755.26006243, 1958.94680308, 1939.91856272,
       1644.51761083, 1656.65355052, 1649.04240637, 1545.28653441,
       1745.03548444, 1522.71775618, 1541.99214238, 1573.00532408])

In [10]:
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import mean_absolute_error

# Calculate MAE
mae = mean_absolute_error(y_test, svr_predictions)
mape = np.mean(np.abs((y_test - svr_predictions) / y_test)) * 100

# Print the result

# Print or use the MAE value
mse = mean_squared_error(y_test, svr_predictions)
rmse = np.sqrt(mse)
def symmetric_mean_absolute_percentage_error(y_test, svr_predictions):
    # Avoiding division by zero
    y_test, svr_pred = np.array(y_test), np.array(svr_predictions)
    mask = y_test != 0
    y_test, svr_predictions = y_test[mask], svr_predictions[mask]

    # Calculate sMAPE
    smape = 2 * np.mean(np.abs(svr_predictions - y_test) / (np.abs(svr_predictions) + np.abs(y_test))) * 100

    return smape
smape_value = symmetric_mean_absolute_percentage_error(y_test, svr_predictions)
r2 = r2_score(y_test, svr_predictions)
print(f"Mean Squared Error: {mse:.2f}")
print(f"Root Mean Squared Error: {rmse:.2f}")
print(f"R-squared: {r2:.2f}")
print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")
print(f"Symmetric Mean absolute percentage error(sMAPE): {smape_value:.2f}%")

Mean Squared Error: 1387.91
Root Mean Squared Error: 37.25
R-squared: 0.96
Mean Absolute Error (MAE): 23.81
Mean Absolute Percentage Error (MAPE): 1.38%
Symmetric Mean absolute percentage error(sMAPE): 1.37%


In [11]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=10, random_state=42)
regressor.fit(X_train, y_train)
rf_predictions = regressor.predict(X_test)

In [12]:
rf_predictions

array([1975.3, 1749.7, 1833. , 1613.4, 1658.4, 1570.4, 1681.2, 1542.9,
       1768.8, 1531.5, 1536.1, 1571.7])

In [13]:
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import mean_absolute_error

# Calculate MAE
mae = mean_absolute_error(y_test,rf_predictions)

# Print or use the MAE value
mse = mean_squared_error(y_test,rf_predictions)
rmse = np.sqrt(mse)
mape = np.mean(np.abs((y_test - rf_predictions) / y_test)) * 100

def symmetric_mean_absolute_percentage_error(y_test, rf_predictions):
    # Avoiding division by zero
    y_test, y_pred = np.array(y_test), np.array(rf_predictions)
    mask = y_test != 0
    y_test, rf_predictions = y_test[mask], rf_predictions[mask]

    # Calculate sMAPE
    smape = 2 * np.mean(np.abs(rf_predictions - y_test) / (np.abs(rf_predictions) + np.abs(y_test))) * 100

    return smape

# Calculate sMAPE
smape_value = symmetric_mean_absolute_percentage_error(y_test, rf_predictions)

r2 = r2_score(y_test,rf_predictions)
print(f"Mean Squared Error: {mse:.2f}")
print(f"Root Mean Squared Error: {rmse:.2f}")
print(f"R-squared: {r2:.2f}")
print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")
print(f"Symmetric Mean absolute percentage error(sMAPE): {smape_value:.2f}%")

Mean Squared Error: 12695.06
Root Mean Squared Error: 112.67
R-squared: 0.59
Mean Absolute Error (MAE): 55.00
Mean Absolute Percentage Error (MAPE): 2.86%
Symmetric Mean absolute percentage error(sMAPE): 3.04%


In [14]:
from sklearn.neighbors import KNeighborsRegressor
knr = KNeighborsRegressor(n_neighbors=5, algorithm = 'auto')
knr.fit(X_train, y_train)

KNeighborsRegressor()

In [15]:
knn_predictions = knr.predict(X_test)
mae = mean_absolute_error(y_test, knn_predictions)

# Print or use the MAE value
mse = mean_squared_error(y_test, knn_predictions)
rmse = np.sqrt(mse)
mape = np.mean(np.abs((y_test -knn_predictions) / y_test)) * 100

def symmetric_mean_absolute_percentage_error(y_test, knn_predictions):
    # Avoiding division by zero
    y_test, y_pred = np.array(y_test), np.array(knn_predictions)
    mask = y_test != 0
    y_test, knn_predictions = y_test[mask], knn_predictions[mask]

    # Calculate sMAPE
    smape = 2 * np.mean(np.abs(knn_predictions -y_test) / (np.abs(knn_predictions) + np.abs(y_test))) * 100

    return smape

# Calculate sMAPE
smape_value = symmetric_mean_absolute_percentage_error(y_test, knn_predictions)

r2 = r2_score(y_test,knn_predictions)
print(f"Mean Squared Error: {mse:.2f}")
print(f"Root Mean Squared Error: {rmse:.2f}")
print(f"R-squared: {r2:.2f}")
print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")
print(f"Symmetric Mean absolute percentage error(sMAPE): {smape_value:.2f}%")

Mean Squared Error: 5054.70
Root Mean Squared Error: 71.10
R-squared: 0.84
Mean Absolute Error (MAE): 52.05
Mean Absolute Percentage Error (MAPE): 2.89%
Symmetric Mean absolute percentage error(sMAPE): 2.89%


In [16]:
knn_predictions

array([1936.4, 1906. , 1936.4, 1825.8, 1784.4, 1565.6, 1687.2, 1543.6,
       1650. , 1543.6, 1553.6, 1568.8])

In [17]:
from sklearn.neural_network import MLPRegressor
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
# X, y = make_regression(n_samples=200, random_state=1)
# X_train, X_test, y_train, y_test = train_test_split(X, y,
regr = MLPRegressor(random_state=42)

In [18]:
param_grid = {
    'hidden_layer_sizes': [(50,), (100,), (50, 50), (100, 50, 25), (100, 100, 50, 25)],
    'activation':['relu', 'tanh'],
    'alpha': [0.0001, 0.001, 0.01],
    'learning_rate': ['constant', 'invscaling', 'adaptive'],
    'max_iter': [1000, 2000, 3000]
}

grid_search = GridSearchCV(estimator=regr, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)

# Fit the grid search object to the training data
grid_search.fit(X_train, y_train)

# Get the best hyperparameters and the best estimator from the grid search
best_params = grid_search.best_params_
best_estimator = grid_search.best_estimator_

# Evaluate the best estimator on the test data
ann_predictions = best_estimator.predict(X_test)

In [19]:
ann_predictions

array([1831.84363739, 1769.0710101 , 1823.831087  , 1818.0354725 ,
       1735.50153829, 1733.6688791 , 1733.10041646, 1702.71099512,
       1760.78967848, 1696.29962189, 1702.27840008, 1711.60872938])

In [20]:
mae = mean_absolute_error(y_test, ann_predictions)

# Print or use the MAE value
mse = mean_squared_error(y_test,ann_predictions)
rmse = np.sqrt(mse)
mape = np.mean(np.abs((y_test - ann_predictions) /y_test)) * 100
r2 = r2_score(y_test, ann_predictions)

def symmetric_mean_absolute_percentage_error(y_test, ann_predictions):
    # Avoiding division by zero
    y_test, ann_predictions = np.array(y_test), np.array(ann_predictions)
    mask =y_test!= 0
    y_test, ann_predictions = y_test[mask],ann_predictions[mask]

    # Calculate sMAPE
    smape = 2 * np.mean(np.abs(ann_predictions - y_test) / (np.abs(ann_predictions) + np.abs(y_test))) * 100

    return smape

# Calculate sMAPE
smape_value = symmetric_mean_absolute_percentage_error(y_test, ann_predictions)

print(f"Mean Squared Error: {mse:.2f}")
print(f"Root Mean Squared Error: {rmse:.2f}")
print(f"R-squared: {r2:.2f}")
print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")
print(f"Symmetric Mean absolute percentage error(sMAPE): {smape_value:.2f}%")

Mean Squared Error: 18165.37
Root Mean Squared Error: 134.78
R-squared: 0.42
Mean Absolute Error (MAE): 123.10
Mean Absolute Percentage Error (MAPE): 7.28%
Symmetric Mean absolute percentage error(sMAPE): 7.14%


In [21]:
import numpy as np
from scipy.optimize import minimize
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.neighbors import KNeighborsRegressor
# Combine the predictions into a list
model_predictions = [svr_predictions, rf_predictions, knn_predictions, ann_predictions]

# Concatenate the predictions from all models for the test set
def combined_predictions(weights, *args):
    model_predictions = args
    return np.dot(weights, model_predictions)

# Objective function to minimize (RMSE)
def objective_function(weights, *args):
    y_test, model_predictions = args
    combined_pred = combined_predictions(weights, *model_predictions)
    rmse = np.sqrt(mean_squared_error(y_test, combined_pred))
    return rmse

# Constraints for weights
constraints = ({'type': 'eq', 'fun': lambda w: 1 - sum(w)})

# Initial guess for weights
initial_weights = np.ones(len(model_predictions)) / len(model_predictions)
# Minimize the objective function
result = minimize(objective_function, initial_weights, args=(y_test, model_predictions), constraints=constraints, bounds=[(0, 1)] * len(model_predictions))

# Extract the optimized weights
optimized_weights = result.x

# Combined prediction using optimized weights
final_combined_pred = combined_predictions(optimized_weights, *model_predictions)

# Evaluate the final RMSE
print(final_combined_pred)
final_rmse = np.sqrt(mean_squared_error(y_test, final_combined_pred))
final_mae = np.mean(np.abs(y_test - final_combined_pred))
print(f'Optimized Weights: {optimized_weights}')
print(f'Final RMSE: {final_rmse}')
print(f'Final MAE: {final_mae}')

[1976.62998909 1788.02161375 1954.04652081 1915.11623625 1674.91940179
 1636.86413299 1657.33551027 1544.91998603 1724.38064044 1527.25626612
 1544.51497364 1572.09134641]
Optimized Weights: [7.82661769e-01 1.62285101e-11 2.17338230e-01 3.41233208e-11]
Final RMSE: 32.88684486699511
Final MAE: 25.237741962950793


In [22]:
import numpy as np
from scipy.optimize import minimize
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Objective function to minimize (MAE)
def objective_function(weights, *args):
    y_test, model_predictions = args
    combined_pred = np.dot(weights, model_predictions)
    mae = np.mean(np.abs(y_test - combined_pred))
    return mae

# Additional constraint
def additional_constraint(weights, y_test, model_predictions):
    combined_pred = np.dot(weights, model_predictions)
    rmse = np.sqrt(mean_squared_error(y_test, combined_pred))
    return 32.88684486699511-rmse

# Constraints for weights
constraints = [{'type': 'eq', 'fun': lambda w: 1 - sum(w)},
               {'type': 'ineq', 'fun': lambda w: w},
               {'type': 'ineq', 'fun': lambda w: additional_constraint(w, y_test, model_predictions)}]

# Initial guess for weights
initial_weights = np.ones(len(model_predictions)) / len(model_predictions)

# Minimize the objective function
result = minimize(objective_function, initial_weights, args=(y_test, model_predictions), constraints=constraints)

# Extract the optimized weights
optimized_weights = result.x

# Combined prediction using optimized weights
final_combined_pred = np.dot(optimized_weights, model_predictions)

# Evaluate the final MAE and RMSE
final_mae = np.mean(np.abs(y_test - final_combined_pred))
final_rmse = np.sqrt(mean_squared_error(y_test, final_combined_pred))

# Print the results
print(f'Optimized Weights: {optimized_weights}')
print(f'Final MAE: {final_mae}')
print(f'Final RMSE: {final_rmse}')

Optimized Weights: [ 7.82705131e-01 -6.47639904e-10  2.17294870e-01 -1.62399527e-10]
Final MAE: 25.237098593955086
Final RMSE: 32.886844986486956
